---
name: Continuous Delivery

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name:
        ${{
          ((github.ref_name == 'main') || startsWith('releases/', github.ref_name))
          && github.ref_name
          || null
        }}
    steps:
      - run: echo ref_name is ${{ github.ref_name }}, ref is ${{ github.ref }}
      - run: echo ${{ vars.ECHO_THIS }}
